name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore build/Kyameru.Component.File.sln
    - name: Build
      run: dotnet build build/Kyameru.Component.File.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test tests/Kyameru.Component.File.Tests/Kyameru.Component.File.Tests.csproj --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=TestCoverage/
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./tests/Kyameru.Component.File.Tests/TestCoverage/coverage.info
